### ISSUE TITLE
Past grades not showing

### ISSUE THREAD

**Issue by gadhagod** [Dixits1/sc-grade-displayer#4]
This may be intentional, but grades under the "past" tab do not show.
![Screen Shot 2021-01-25 at 7 51 59 AM](https://user-images.githubusercontent.com/69025547/105729564-3b925e00-5ee2-11eb-822a-27620b223c9e.png)

I understand that it might not be possible to have this happen.

**Comment by Dixits1** [comment]
Unfortunately, Google has tightened restrictions on the webstore, requiring me to fill out a bunch of fields regarding the app's various permissions and uses. This has made it difficult for me to update the app as I haven't found the time to fill out these forms, and while I have already added this change in development, it has not made it to production for this reason. I will likely update the extension publicly sometime next week once I finish filling out those forms. Apologies for the inconveniences.

**Comment by gadhagod** [comment]
No problem, no pressure.
